// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddCart struct {
	UserID string `json:"userID"`
	Sku    string `json:"sku"`
	Qty    int    `json:"qty"`
}

type AddProductStock struct {
	Sku string `json:"sku"`
	Qty int    `json:"qty"`
}

type Cart struct {
	ID     string     `json:"id"`
	UserID string     `json:"userID"`
	Items  []*Product `json:"items"`
}

type NewProduct struct {
	Sku   string  `json:"sku"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Qty   int     `json:"qty"`
}

type Product struct {
	Sku   string  `json:"sku"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Qty   int     `json:"qty"`
}

type User struct {
	ID   string `json:"ID"`
	Name string `json:"name"`
}
