name: CI Test Application

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Setup Go Executable Client
        uses: actions/setup-go@v3
      - name: Run Test Command
        run: make test
      - name: Archive Code Coverage Result
        uses: actions/upload-artifact@v3
        with:
          name: Code-Coverage-Report
          path: coverage/coverage.out